<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_DE">
<context>
    <name>@default</name>
    <message>
        <location filename="../massenermittlung.py" line="128"/>
        <source>RuntimeError</source>
        <comment>Failed to create the plugin menu.</comment>
        <translation>Konnte das plugin-Menu nicht erstellen.</translation>
    </message>
    <message>
        <location filename="../massenermittlung.py" line="218"/>
        <source>Massenermittlung</source>
        <comment>Success</comment>
        <translation>Erfolg</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="67"/>
        <source>RuntimeError</source>
        <comment>Failed to start editing the new layer.</comment>
        <translation>Konnte den neuen Layer nicht in den Bearbeitungsstatus versetzen.</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="83"/>
        <source>RuntimeError</source>
        <comment>Failed to commit changes to the new layer.</comment>
        <translation>Konnte die Änderungen nicht im neuen Layer speichern.</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="95"/>
        <source>RuntimeError</source>
        <comment>No features found in the selected layer.</comment>
        <translation>Im gewählten Layer konnten keine Objekte gefunden werden.</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="194"/>
        <source>log</source>
        <comment>house connections</comment>
        <translation>Hausanschlüsse</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="277"/>
        <source>log</source>
        <comment>T-pieces</comment>
        <translation>T-Stücke</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="461"/>
        <source>log</source>
        <comment>bends</comment>
        <translation>Bögen</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="126"/>
        <source>RuntimeError</source>
        <comment>No QGIS project is currently open.</comment>
        <translation>Es ist kein QGIS-Projekt geöffnet.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="145"/>
        <source>RuntimeError</source>
        <comment>Project is not saved. Please save the project first.</comment>
        <translation>Das Projekt ist noch nicht abgespeichert.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="190"/>
        <source>RuntimeError</source>
        <comment>Selected layer is not set.</comment>
        <translation>Der gewählte Layer ist nicht gesetzt.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="320"/>
        <source>RuntimeError</source>
        <comment>QGIS interface not set.</comment>
        <translation>Die QGIS-Benutzeroberfläche ist nicht gesetzt.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="209"/>
        <source>RuntimeError</source>
        <comment>New layer is not set.</comment>
        <translation>Der neue Layer ist nicht gesetzt.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="323"/>
        <source>RuntimeError</source>
        <comment>Could not get layer tree view.</comment>
        <translation>Konnte nicht auf den Layerbaum zugreifen.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="327"/>
        <source>UserError</source>
        <comment>Multiple layers selected.</comment>
        <translation>Mehrere Layer ausgewählt. (Bitte nur einen einzelnen Layer auswählen)</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="329"/>
        <source>UserError</source>
        <comment>No layer selected.</comment>
        <translation>Kein Layer ausgewählt. (Bitte den Layer wählen, der untersucht werden soll)</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="333"/>
        <source>UserError</source>
        <comment>Selected node is not a layer.</comment>
        <translation>Das ausgewälte Objekt ist kein Layer. (Es können nur Linien-Vektorlayer untersucht werden)</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="337"/>
        <source>UserError</source>
        <comment>Selected layer is not a vector layer.</comment>
        <translation>Der ausgewählte Layer ist kein Vektorlayer. (Es können nur Linien-Vektorlayer untersucht werden)</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="340"/>
        <source>UserError</source>
        <comment>The selected layer is not a line layer.</comment>
        <translation>Der ausgewählte Layer ist kein Linienlayer. (Es können nur Linien-Vektorlayer untersucht werden)</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="395"/>
        <source>RuntimeError</source>
        <comment>Could not get layer tree root.</comment>
        <translation>Konnte nicht auf den Layerbaum zugreifen.</translation>
    </message>
    <message>
        <location filename="../massenermittlung.py" line="196"/>
        <source>Massenermittlung</source>
        <comment>Bulk assessment for layer &apos;{0}&apos; completed</comment>
        <translation>Untersuchung des Layers '{0}' abgeschlossen.</translation>
    </message>
    <message>
        <location filename="../modules/find_stuff.py" line="98"/>
        <source>log</source>
        <comment>Found {0} lines in the selected layer.</comment>
        <translation>{0} Linien im gewählten Layer gefunden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="54"/>
        <source>log</source>
        <comment>Search for '{0}': {1} lines checked → {2} items found.</comment>
        <translation>{0}: {1} Linien untersucht → {2} gefunden</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="62"/>
        <source>log</source>
        <comment>Search for '{0}': {1} lines checked → No items found.</comment>
        <translation>{0}: {1} Linien untersucht → keine gefunden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="156"/>
        <source>RuntimeError</source>
        <comment>Failed to create GeoPackage at: {0}</comment>
        <translation>Konnte Geopackage '{0}' nicht erstellen.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="363"/>
        <source>RuntimeError</source>
        <comment>Could not get data provider for layer: {0}</comment>
        <translation>Konnte nicht auf die Daten von Layer '{0}' zugreifen.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="296"/>
        <source>log</source>
        <comment>Feature {0} could not be reprojected.</comment>
        <translation>Das Objekt mit der ID {0} konnte nicht reprojiziert werden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="382"/>
        <source>log</source>
        <comment>Empty layer created: {0}</comment>
        <translation>Leerer Layer '{0}' erstellt.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="387"/>
        <source>RuntimeError</source>
        <comment>Failed to create empty layer &apos;{0}&apos; - Error: {1}</comment>
        <translation>Konnte leeren Layer '{0}' nicht erstellen. Fehler: {1}</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="402"/>
        <source>RuntimeError</source>
        <comment>Could not find layer &apos;{0}&apos; in GeoPackage &apos;{1}&apos;</comment>
        <translation>Konnte den Layer '{0}' nicht im GeoPackage '{1}' finden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="413"/>
        <source>log</source>
        <comment>Added {0} from the GeoPackage to the project.</comment>
        <translation>Layer '{0}' zum GeoPackage des Projekts hinzugefügt.</translation>
    </message>
</context>
</TS>
