<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_DE">
<context>
    <name>UserError</name>
    <message>
        <location filename="../modules/general.py" line="357"/>
        <source>Multiple layers selected.</source>
        <translation>Mehrere Layer ausgewählt. Bitte nur einen Layer für die Verarbeitung wählen.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="361"/>
        <source>No layer selected.</source>
        <translation>Kein Layer ausgewählt. Bitte einen Layer für die Verarbeitung wählen.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="367"/>
        <source>Selected node is not a layer.</source>
        <translation>Das ausgewählte Objekt ist kein Layer. Es können nur Vektorlayer mit Linien-Geometrie verarbeitet werden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="373"/>
        <source>Selected layer is not a vector layer.</source>
        <translation>Der gewählte Layer ist kein Vektorlayer. Es können nur Vektorlayer mit Linien-Geometrie verarbeitet werden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="380"/>
        <source>The selected layer is not a line layer.</source>
        <translation>Der gewählte Layer ist kein Linien-Layer. Es können nur Vektorlayer mit Linien-Geometrie verarbeitet werden.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="57"/>
        <source>No QGIS project is currently open.</source>
        <translation>Kein QGSI-Projekt geöffnet.</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="102"/>
        <source>Project is not saved. Please save the project first.</source>
        <translation>Das Projekt ist noch nicht gespeichert. Bitte das Projekt abspeichern, damit ein Projektordner erstellt wird.</translation>
    </message>
</context>
<context>
    <name>progress_bar</name>
    <message>
        <location filename="../massenermittlung.py" line="250"/>
        <source>Performing bulk assessment...</source>
        <translation>Verarbeite Leitungsnetz...</translation>
    </message>
    <message>
        <location filename="../modules/general.py" line="504"/>
        <source>Writing results to new layer...</source>
        <translation>Schreibe Ergebnisse in neuen Layer...</translation>
    </message>
    <message>
        <location filename="../modules/poi_classifier.py" line="58"/>
        <source>Collecting points...</source>
        <translation>Zu untersuchende Punkte werden gesammelt...</translation>
    </message>
    <message>
        <location filename="../modules/poi_classifier.py" line="82"/>
        <source>Analyzing points...</source>
        <translation>Untersuche Punkte...</translation>
    </message>
</context>
<context>
    <name>questionable_note</name>
    <message>
        <location filename="../modules/poi_classifier.py" line="71"/>
        <source>Intersection without endpoints</source>
        <translation>Linien schneiden sich ohne Endpunkt</translation>
    </message>
    <message>
        <location filename="../modules/poi_classifier.py" line="132"/>
        <source>More than three lines at intersection</source>
        <translation>Mehr als 3 Linien am Knoten - bitte Knoten bearbeiten</translation>
    </message>
    <message>
        <location filename="../modules/poi_classifier.py" line="183"/>
        <source>Unconnected line</source>
        <translation>Linie nicht mit Netz verbunden</translation>
    </message>
    <message>
        <location filename="../modules/poi_classifier.py" line="205"/>
        <source>Endpoint near intersection</source>
        <translation>Endpunkt sehr nah, aber nicht ganz an Knoten</translation>
    </message>
</context>
<context>
    <name>summary</name>
    <message>
        <location filename="../modules/logs_and_errors.py" line="147"/>
        <source>Bulk assessment for layer &apos;{0}&apos; completed </source>
        <translation>Überprüfung des Layers '{0}' abgeschlossen </translation>
    </message>
    <message>
        <location filename="../modules/logs_and_errors.py" line="153"/>
        <source>Type field not found in new layer.</source>
        <translation>Konnte die Spalte für den Formteiltyp nicht finden.</translation>
    </message>
    <message>
        <location filename="../modules/logs_and_errors.py" line="166"/>
        <source>Failed to get type counts from new layer.</source>
        <translation>Konnte die Anlagenteile nicht auszählen.</translation>
    </message>
</context>
</TS>
